# TCL File Generated by Component Editor 23.1
# Sat Feb 17 19:10:59 MST 2024
# DO NOT MODIFY


# 
# ad1939_audio_mini "AD1939_Audio_Mini" v1.0
# Lucas Ritzdorf 2024.02.17.19:10:59
# Interface for the AD1939 audio codec chip, as used on the SensorLogic Audio Mini
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ad1939_audio_mini
# 
set_module_property DESCRIPTION "Interface for the AD1939 audio codec chip, as used on the SensorLogic Audio Mini"
set_module_property NAME ad1939_audio_mini
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols/Audio & Video"
set_module_property AUTHOR "Lucas Ritzdorf"
set_module_property DISPLAY_NAME AD1939_Audio_Mini
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ad1939_hps_audio_mini
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ad1939_hps_audio_mini.vhd VHDL PATH ad1939_hps_audio_mini.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point from_line_in
# 
add_interface from_line_in avalon_streaming start
set_interface_property from_line_in associatedClock sys_clk
set_interface_property from_line_in associatedReset sys_reset
set_interface_property from_line_in dataBitsPerSymbol 24
set_interface_property from_line_in errorDescriptor ""
set_interface_property from_line_in firstSymbolInHighOrderBits true
set_interface_property from_line_in maxChannel 1
set_interface_property from_line_in readyLatency 0
set_interface_property from_line_in ENABLED true
set_interface_property from_line_in EXPORT_OF ""
set_interface_property from_line_in PORT_NAME_MAP ""
set_interface_property from_line_in CMSIS_SVD_VARIABLES ""
set_interface_property from_line_in SVD_ADDRESS_GROUP ""

add_interface_port from_line_in ad1939_adc_channel channel Output 1
add_interface_port from_line_in ad1939_adc_data data Output 24
add_interface_port from_line_in ad1939_adc_valid valid Output 1


# 
# connection point sys_clk
# 
add_interface sys_clk clock end
set_interface_property sys_clk clockRate 98304000
set_interface_property sys_clk ENABLED true
set_interface_property sys_clk EXPORT_OF ""
set_interface_property sys_clk PORT_NAME_MAP ""
set_interface_property sys_clk CMSIS_SVD_VARIABLES ""
set_interface_property sys_clk SVD_ADDRESS_GROUP ""

add_interface_port sys_clk sys_clk clk Input 1


# 
# connection point sys_reset
# 
add_interface sys_reset reset end
set_interface_property sys_reset associatedClock sys_clk
set_interface_property sys_reset synchronousEdges DEASSERT
set_interface_property sys_reset ENABLED true
set_interface_property sys_reset EXPORT_OF ""
set_interface_property sys_reset PORT_NAME_MAP ""
set_interface_property sys_reset CMSIS_SVD_VARIABLES ""
set_interface_property sys_reset SVD_ADDRESS_GROUP ""

add_interface_port sys_reset sys_reset reset Input 1


# 
# connection point abclk
# 
add_interface abclk clock end
set_interface_property abclk clockRate 12288000
set_interface_property abclk ENABLED true
set_interface_property abclk EXPORT_OF ""
set_interface_property abclk PORT_NAME_MAP ""
set_interface_property abclk CMSIS_SVD_VARIABLES ""
set_interface_property abclk SVD_ADDRESS_GROUP ""

add_interface_port abclk ad1939_adc_abclk clk Input 1


# 
# connection point alrclk
# 
add_interface alrclk clock end
set_interface_property alrclk clockRate 192000
set_interface_property alrclk ENABLED true
set_interface_property alrclk EXPORT_OF ""
set_interface_property alrclk PORT_NAME_MAP ""
set_interface_property alrclk CMSIS_SVD_VARIABLES ""
set_interface_property alrclk SVD_ADDRESS_GROUP ""

add_interface_port alrclk ad1939_adc_alrclk clk Input 1


# 
# connection point to_headphone_out
# 
add_interface to_headphone_out avalon_streaming end
set_interface_property to_headphone_out associatedClock sys_clk
set_interface_property to_headphone_out associatedReset sys_reset
set_interface_property to_headphone_out dataBitsPerSymbol 24
set_interface_property to_headphone_out errorDescriptor ""
set_interface_property to_headphone_out firstSymbolInHighOrderBits true
set_interface_property to_headphone_out maxChannel 1
set_interface_property to_headphone_out readyLatency 0
set_interface_property to_headphone_out ENABLED true
set_interface_property to_headphone_out EXPORT_OF ""
set_interface_property to_headphone_out PORT_NAME_MAP ""
set_interface_property to_headphone_out CMSIS_SVD_VARIABLES ""
set_interface_property to_headphone_out SVD_ADDRESS_GROUP ""

add_interface_port to_headphone_out ad1939_dac_channel channel Input 1
add_interface_port to_headphone_out ad1939_dac_data data Input 24
add_interface_port to_headphone_out ad1939_dac_valid valid Input 1


# 
# connection point physical
# 
add_interface physical conduit end
set_interface_property physical associatedClock sys_clk
set_interface_property physical associatedReset sys_reset
set_interface_property physical ENABLED true
set_interface_property physical EXPORT_OF ""
set_interface_property physical PORT_NAME_MAP ""
set_interface_property physical CMSIS_SVD_VARIABLES ""
set_interface_property physical SVD_ADDRESS_GROUP ""

add_interface_port physical ad1939_adc_asdata2 asdata2 Input 1
add_interface_port physical ad1939_dac_dbclk dbclk Output 1
add_interface_port physical ad1939_dac_dlrclk dlrclk Output 1
add_interface_port physical ad1939_dac_dsdata1 dsdata1 Output 1

